# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: deploy

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow.run.conclussion}}=="success"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - run: aws deploy create-deployment --application-name ww --deployment-group-name wwe --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
          